"""500 diverse LinkedIn content ideas organized into 50 categories (10 each)."""

TOPICS = {
    "Leadership": [
        "Share a leadership lesson you learned from your worst boss",
        "Describe the moment you realized leadership is about listening, not talking",
        "Explain why the best leaders make themselves replaceable",
        "Share a time when admitting you were wrong made you a stronger leader",
        "Discuss why micromanagement is the fastest way to lose your best people",
        "Talk about the difference between being a boss and being a leader",
        "Share 3 habits that transformed your leadership style",
        "Explain why vulnerability is a leadership superpower, not a weakness",
        "Describe how you handle making unpopular decisions as a leader",
        "Share the best leadership advice you ever received and how it changed you",
    ],
    "Career Growth": [
        "Share the unconventional career move that changed your trajectory",
        "Explain why lateral moves can be more valuable than promotions",
        "Discuss the skill that 10x'd your career that they don't teach in school",
        "Share how you navigated a career pivot after 5+ years in one field",
        "Talk about the importance of having a career sponsor, not just a mentor",
        "Explain why saying no to opportunities is sometimes the best career move",
        "Share 3 signs it's time to leave a job, even if it's comfortable",
        "Discuss how to negotiate a raise with confidence and data",
        "Share the career mistake you're actually grateful for now",
        "Explain why your network is more important than your resume",
    ],
    "AI and Technology": [
        "Share how AI is changing your industry and what professionals should do about it",
        "Discuss the AI skills every professional needs in the next 2 years",
        "Explain why AI won't replace you, but someone using AI will",
        "Share a practical AI tool that saved you 10+ hours last week",
        "Talk about the ethical considerations of AI in the workplace",
        "Discuss the gap between AI hype and AI reality in your industry",
        "Share how you're using AI to augment your work, not automate it",
        "Explain why understanding AI basics is the new digital literacy",
        "Discuss the jobs AI is creating that didn't exist 2 years ago",
        "Share your honest take on AI's impact on knowledge workers",
    ],
    "Productivity": [
        "Share the one productivity hack that actually stuck with you",
        "Explain why being busy is not the same as being productive",
        "Discuss how you structure your day for deep work vs. shallow work",
        "Share the morning routine that transformed your workday",
        "Talk about why saying no to meetings was the best productivity decision you made",
        "Explain the 2-minute rule and how it changed your workflow",
        "Share how you manage email without letting it control your day",
        "Discuss why multitasking is a myth and what to do instead",
        "Share 3 tools that genuinely improved your productivity (not just hype)",
        "Explain why taking breaks actually makes you more productive",
    ],
    "Hiring and Recruiting": [
        "Share the biggest red flag you look for in interviews",
        "Discuss why the traditional interview process is broken",
        "Explain the hiring mistake that taught you the most",
        "Share how to spot a great candidate beyond their resume",
        "Talk about why culture fit is overrated — culture add is what matters",
        "Discuss the one question you ask in every interview and why",
        "Share how to write job descriptions that attract top talent",
        "Explain why the candidate experience matters more than companies think",
        "Discuss how to hire for potential, not just experience",
        "Share your take on take-home assignments vs. whiteboard interviews",
    ],
    "Remote Work": [
        "Share your honest take on remote work after 3+ years",
        "Discuss the loneliness epidemic in remote work and how to combat it",
        "Explain how to build team culture when everyone is remote",
        "Share the remote work boundary that saved your mental health",
        "Talk about the biggest misconception about remote workers",
        "Discuss how to stay visible and advance your career while working remotely",
        "Share your home office setup evolution and what actually mattered",
        "Explain why asynchronous communication is the key to remote work success",
        "Discuss the future of hybrid work and what companies are getting wrong",
        "Share how to onboard new employees effectively in a remote environment",
    ],
    "Personal Branding": [
        "Share how building a personal brand on LinkedIn changed your career",
        "Discuss why authenticity beats perfection in personal branding",
        "Explain the personal brand framework that helped you stand out",
        "Share 3 mistakes people make when trying to build their personal brand",
        "Talk about how to find your unique voice in a crowded space",
        "Discuss why consistency matters more than virality for personal branding",
        "Share how to define your personal brand in one sentence",
        "Explain the content pillars strategy for personal branding",
        "Discuss how personal branding helped you land opportunities you never applied for",
        "Share the moment you realized your personal brand was actually working",
    ],
    "Startup Lessons": [
        "Share the hardest lesson from your first year running a startup",
        "Discuss why most startups fail and what yours taught you about survival",
        "Explain the fundraising lesson they don't teach in accelerators",
        "Share a lesson about failing fast and pivoting in startups",
        "Talk about the co-founder conflict that almost killed your startup",
        "Discuss the startup metric that matters more than revenue in the early days",
        "Share how you found product-market fit (or haven't yet)",
        "Explain why building in public helped your startup more than stealth mode",
        "Discuss the moment you realized your original idea was wrong",
        "Share the bootstrapping hack that saved your startup thousands",
    ],
    "Networking": [
        "Share 3 tips for networking at tech conferences without being awkward",
        "Discuss why giving before asking is the golden rule of networking",
        "Explain how one LinkedIn connection changed the course of your career",
        "Share the networking mistake most professionals make at events",
        "Talk about how to follow up after meeting someone without being pushy",
        "Discuss why your weak ties are more valuable than your close network",
        "Share how to build genuine relationships, not just collect connections",
        "Explain the art of the warm introduction and why it works",
        "Discuss how to network effectively as an introvert",
        "Share the cold outreach message that actually got a response",
    ],
    "Management": [
        "Share the first lesson you learned as a new manager",
        "Discuss why the best managers coach, they don't direct",
        "Explain how to give feedback that people actually act on",
        "Share how you handle underperforming team members with empathy",
        "Talk about the 1-on-1 meeting structure that transformed your team",
        "Discuss why new managers should stop trying to be friends with their reports",
        "Share how to build psychological safety on your team",
        "Explain the delegation mistake that most new managers make",
        "Discuss how to manage up effectively without being a yes-person",
        "Share the management book or framework that changed your approach",
    ],
    "Communication Skills": [
        "Share the communication tip that made you a better professional",
        "Discuss why listening is the most underrated professional skill",
        "Explain how to give a presentation that people actually remember",
        "Share how to write emails that get responses",
        "Talk about the art of saying no professionally",
        "Discuss why overcommunication is usually better than undercommunication",
        "Share how to navigate difficult conversations at work",
        "Explain the framework for giving clear, actionable feedback",
        "Discuss how to communicate bad news to your team or stakeholders",
        "Share the public speaking hack that eliminated your stage fright",
    ],
    "Entrepreneurship": [
        "Share the moment you decided to leave your corporate job and start a business",
        "Discuss the financial reality of entrepreneurship nobody talks about",
        "Explain why your first customers are more important than your first investors",
        "Share the sales lesson every entrepreneur needs to learn",
        "Talk about work-life balance as an entrepreneur — does it exist?",
        "Discuss why most business plans don't survive first contact with customers",
        "Share the partnership decision that made or broke your business",
        "Explain how to validate a business idea before quitting your job",
        "Discuss the loneliness of entrepreneurship and how you cope",
        "Share the customer feedback that completely changed your business direction",
    ],
    "Mental Health at Work": [
        "Share how you recognized burnout before it was too late",
        "Discuss why we need to normalize mental health conversations at work",
        "Explain the boundary you set that protected your mental health",
        "Share how your company's approach to mental health changed your perspective",
        "Talk about the connection between perfectionism and burnout",
        "Discuss how to support a colleague who's struggling without overstepping",
        "Share the signs of workplace burnout that people often ignore",
        "Explain why 'just push through it' is the worst advice for burnout",
        "Discuss how leaders can create a culture that supports mental well-being",
        "Share the conversation about mental health at work that changed everything",
    ],
    "Diversity and Inclusion": [
        "Share what you've learned about being a better ally at work",
        "Discuss why diverse teams outperform homogeneous ones (with examples)",
        "Explain the difference between diversity and true inclusion",
        "Share the moment you realized your workplace wasn't as inclusive as you thought",
        "Talk about how to address unconscious bias in hiring",
        "Discuss why representation in leadership matters for everyone",
        "Share a specific action companies can take to improve inclusion today",
        "Explain why DEI initiatives fail and what actually works",
        "Discuss how to be an effective ally without centering yourself",
        "Share how your perspective on workplace diversity has evolved over time",
    ],
    "Sales and Business Development": [
        "Share the sales technique that changed your close rate overnight",
        "Discuss why the best salespeople are actually great listeners",
        "Explain the follow-up strategy that tripled your response rate",
        "Share the cold email template that actually gets replies",
        "Talk about how to handle rejection in sales without taking it personally",
        "Discuss why selling on value beats selling on price every time",
        "Share the discovery call framework that your prospects actually enjoy",
        "Explain how to build trust with prospects before asking for the sale",
        "Discuss the biggest sales myth that's holding professionals back",
        "Share how storytelling transformed your sales presentations",
    ],
    "Marketing": [
        "Share the marketing campaign that taught you the most about your audience",
        "Discuss why content marketing is a long game most companies abandon too early",
        "Explain the marketing metric that matters more than followers or impressions",
        "Share how to create content that your audience actually wants to consume",
        "Talk about the marketing trend you think is overhyped (and what to focus on instead)",
        "Discuss why understanding your customer's pain points is Marketing 101",
        "Share the A/B test result that surprised you the most",
        "Explain how to measure marketing ROI when attribution is messy",
        "Discuss the rise of creator-led marketing and why it works",
        "Share the brand storytelling lesson every marketer needs",
    ],
    "Work-Life Balance": [
        "Share the moment you realized you were sacrificing too much for work",
        "Discuss why 'hustle culture' is a trap, not a badge of honor",
        "Explain the boundaries you set that improved both your work AND personal life",
        "Share how you disconnect from work when working from home",
        "Talk about the hobby that made you better at your job",
        "Discuss why taking all your vacation days makes you a better employee",
        "Share the conversation with your family that changed how you approach work",
        "Explain why rest is not laziness — it's a strategy",
        "Discuss how to handle a boss who expects you to be available 24/7",
        "Share what you'd tell your younger self about work-life balance",
    ],
    "Data and Analytics": [
        "Share how data-driven decision making transformed your team's results",
        "Discuss the most common data mistakes businesses make",
        "Explain why data literacy is becoming essential for every role",
        "Share a story where the data told a different story than intuition",
        "Talk about how to present data to non-technical stakeholders",
        "Discuss the difference between correlation and causation with a real example",
        "Share the dashboard or metric that changed how your team operates",
        "Explain how to build a data-driven culture without drowning in numbers",
        "Discuss the ethical implications of data collection in business",
        "Share the analytics tool or approach that gave you unexpected insights",
    ],
    "Product Management": [
        "Share the product decision you agonized over and what it taught you",
        "Discuss the difference between what users say they want and what they need",
        "Explain how to prioritize features when everything feels urgent",
        "Share the product launch failure that taught you the most",
        "Talk about how to work with engineering teams as a PM without being annoying",
        "Discuss why talking to customers weekly should be non-negotiable for PMs",
        "Share the product framework that actually helps you make better decisions",
        "Explain how to say no to stakeholders without burning bridges",
        "Discuss the MVP approach — when it works and when it doesn't",
        "Share how you measure product success beyond just revenue",
    ],
    "Design and UX": [
        "Share the UX principle that every non-designer should understand",
        "Discuss why good design is invisible and what that means in practice",
        "Explain the user research method that gave you the biggest insight",
        "Share a design decision that dramatically improved user engagement",
        "Talk about the gap between beautiful design and usable design",
        "Discuss how to advocate for design in engineering-driven organizations",
        "Share the accessibility lesson every product team needs to hear",
        "Explain design thinking in simple terms anyone can apply",
        "Discuss how to give constructive feedback on design without being vague",
        "Share the design trend you think is hurting user experience",
    ],
    "Finance and Money": [
        "Share the financial mistake in your 20s that taught you the most",
        "Discuss why financial literacy should be taught alongside career skills",
        "Explain the investment strategy that works for busy professionals",
        "Share how you negotiated your salary and what you'd do differently",
        "Talk about the financial planning advice you wish you'd received earlier",
        "Discuss why most people underestimate the power of compound interest",
        "Share the budgeting approach that actually stuck with you",
        "Explain how to evaluate equity compensation at a startup",
        "Discuss the financial red flags to watch for when joining a company",
        "Share the money mindset shift that changed your relationship with wealth",
    ],
    "Soft Skills": [
        "Share why empathy is the most undervalued skill in business",
        "Discuss the soft skill that got you promoted more than your technical skills",
        "Explain how to develop emotional intelligence in a professional setting",
        "Share a situation where a soft skill saved a project from failing",
        "Talk about why adaptability is the #1 skill for the future of work",
        "Discuss how to build trust with a new team quickly",
        "Share the conflict resolution technique that actually works",
        "Explain why curiosity is a superpower in any career",
        "Discuss how to develop executive presence without faking it",
        "Share the soft skill you didn't value until it was too late",
    ],
    "Education and Learning": [
        "Share the learning habit that changed your career trajectory",
        "Discuss whether college degrees still matter in your industry",
        "Explain the online course or certification that was actually worth it",
        "Share how you learn new skills effectively as a working professional",
        "Talk about the book that changed your professional perspective",
        "Discuss why teaching others is the best way to master something",
        "Share the unconventional learning resource that surprised you",
        "Explain the concept of learning in public and why it accelerates growth",
        "Discuss how to stay current in a rapidly changing industry",
        "Share the skill you learned outside work that made you better at your job",
    ],
    "Engineering and Development": [
        "Share the coding practice that made you a 10x more effective engineer",
        "Discuss why code reviews are about learning, not gatekeeping",
        "Explain the technical debt lesson every engineering leader should know",
        "Share the debugging technique that saves you hours every week",
        "Talk about the engineering culture practice that improved your team's output",
        "Discuss why documentation is the most underrated engineering skill",
        "Share the system design decision you'd make differently today",
        "Explain how to mentor junior developers effectively",
        "Discuss the importance of testing — when it matters and when it's overkill",
        "Share the technology bet your team made that paid off (or didn't)",
    ],
    "Customer Success": [
        "Share the customer interaction that changed how you do business",
        "Discuss why customer retention is cheaper than customer acquisition",
        "Explain the customer feedback loop that improved your product dramatically",
        "Share how to handle an angry customer and turn them into an advocate",
        "Talk about the customer success metric that matters more than NPS",
        "Discuss why onboarding is the most critical phase of the customer journey",
        "Share the churn pattern you identified and how you fixed it",
        "Explain how to build a customer-centric culture across your organization",
        "Discuss the difference between customer service and customer success",
        "Share the customer story that reminds you why you do what you do",
    ],
    "Public Speaking": [
        "Share the public speaking tip that made the biggest difference for you",
        "Discuss how you prepared for your first major conference talk",
        "Explain why storytelling beats slide decks in most presentations",
        "Share the stage fright hack that actually works",
        "Talk about how to structure a talk that keeps audiences engaged",
        "Discuss why the best speakers practice more than you think",
        "Share the audience interaction technique that transformed your presentations",
        "Explain how to handle tough questions from the audience gracefully",
        "Discuss how public speaking skills transfer to everyday leadership",
        "Share the worst presentation mistake you made and what it taught you",
    ],
    "Innovation": [
        "Share how your company creates space for innovation",
        "Discuss why most innovation initiatives fail and what works instead",
        "Explain the innovation framework that actually produces results",
        "Share a story of innovation coming from an unexpected source",
        "Talk about the balance between innovation and execution",
        "Discuss why constraints drive better innovation than unlimited resources",
        "Share how to foster a culture of experimentation on your team",
        "Explain why failing fast is essential for innovation",
        "Discuss the innovation lesson you learned from a completely different industry",
        "Share the smallest innovation that had the biggest impact on your business",
    ],
    "Project Management": [
        "Share the project management lesson you learned from a failed project",
        "Discuss why most projects fail in planning, not execution",
        "Explain the estimation technique that made your team more accurate",
        "Share how you handle scope creep without damaging stakeholder relationships",
        "Talk about agile vs. waterfall — when each approach actually makes sense",
        "Discuss the meeting structure that made your projects run smoother",
        "Share the project risk you didn't see coming and how you recovered",
        "Explain how to manage cross-functional projects with competing priorities",
        "Discuss why project retrospectives are the most valuable meeting you can have",
        "Share the project management tool or technique that changed your workflow",
    ],
    "Freelancing and Side Hustles": [
        "Share how you landed your first freelance client",
        "Discuss the pricing mistake every new freelancer makes",
        "Explain how to build a side hustle while keeping your full-time job",
        "Share the freelancing boundary that protects your sanity",
        "Talk about how to scope projects to avoid freelance nightmare clients",
        "Discuss when a side hustle should become your main hustle",
        "Share the portfolio strategy that helped you stand out as a freelancer",
        "Explain how to handle clients who want unlimited revisions",
        "Discuss the financial planning basics every freelancer needs",
        "Share the transition from employee to freelancer — what nobody tells you",
    ],
    "Company Culture": [
        "Share what your company's culture actually looks like vs. what's on the website",
        "Discuss why culture is built in the small moments, not the big gestures",
        "Explain how remote work changed your company's culture for better or worse",
        "Share the culture initiative that actually worked (and the ones that didn't)",
        "Talk about how to identify a company's real culture during interviews",
        "Discuss why toxic positivity in the workplace is its own kind of toxic",
        "Share how to preserve culture during rapid growth",
        "Explain why perks aren't culture and what actually is",
        "Discuss the role of psychological safety in team performance",
        "Share the cultural value you care about most and why",
    ],
    "Women in Tech": [
        "Share advice for women navigating male-dominated workplaces",
        "Discuss the gender gap in tech leadership and what's actually changing",
        "Explain how to be a better male ally in the workplace",
        "Share the moment that shaped your perspective on women in tech",
        "Talk about the imposter syndrome challenge and how to overcome it",
        "Discuss the role of mentorship in advancing women in technology",
        "Share the negotiation advice specifically for women in tech",
        "Explain why representation in tech hiring requires systemic changes",
        "Discuss how to build inclusive teams that retain diverse talent",
        "Share the success story that gives you hope for women in tech",
    ],
    "Consulting": [
        "Share the consulting lesson they don't teach in MBA programs",
        "Discuss how to position yourself as an expert consultant in your field",
        "Explain the client management technique that builds long-term relationships",
        "Share the consulting engagement that taught you the most",
        "Talk about how to price consulting services without undervaluing yourself",
        "Discuss the difference between giving advice and driving real change",
        "Share how to handle a client who disagrees with your recommendations",
        "Explain the discovery process that sets consulting projects up for success",
        "Discuss why the best consultants make themselves unnecessary",
        "Share the proposal strategy that wins more consulting contracts",
    ],
    "Content Creation": [
        "Share how you built a content creation habit that stuck",
        "Discuss the content creation myth that's holding most people back",
        "Explain the content repurposing strategy that 5x'd your output",
        "Share the content piece that unexpectedly went viral and what you learned",
        "Talk about how to find your content niche and own it",
        "Discuss why consistency beats quality for building an audience",
        "Share the content creation tool that changed your workflow",
        "Explain how to batch create content without sacrificing quality",
        "Discuss the evolution of content creation from blogs to short-form",
        "Share how content creation opened doors you never expected",
    ],
    "Supply Chain and Operations": [
        "Share the operations lesson that improved efficiency by 10x",
        "Discuss how supply chain disruptions taught your company resilience",
        "Explain the process improvement that your team resisted but ended up loving",
        "Share the automation decision that freed your team for higher-value work",
        "Talk about the operations metric that everyone should track but few do",
        "Discuss lean principles that work outside of manufacturing",
        "Share how to build redundancy in supply chains without killing margins",
        "Explain the vendor management lesson that saved a critical project",
        "Discuss how to identify and eliminate bottlenecks in any process",
        "Share the supply chain innovation that gave your company a competitive edge",
    ],
    "Healthcare Industry": [
        "Share a lesson about innovation in healthcare that applies to any industry",
        "Discuss the biggest technology challenges facing healthcare today",
        "Explain how patient experience principles apply to customer experience",
        "Share the healthcare leadership lesson that works in any sector",
        "Talk about the intersection of AI and healthcare — opportunities and risks",
        "Discuss why healthcare needs more tech talent and how to attract them",
        "Share the telemedicine lesson that changed your view on remote services",
        "Explain how regulatory environments can actually drive innovation",
        "Discuss the mental health crisis in healthcare workers and what leaders can do",
        "Share the healthcare process improvement that saved time and improved outcomes",
    ],
    "Climate and Sustainability": [
        "Share how your company is approaching sustainability beyond greenwashing",
        "Discuss why sustainability is becoming a competitive advantage",
        "Explain the business case for ESG that skeptics need to hear",
        "Share the sustainable business practice that actually saved money",
        "Talk about the role of technology in solving climate challenges",
        "Discuss how professionals can drive sustainability in their organizations",
        "Share the green initiative that had the biggest measurable impact",
        "Explain why every company needs a sustainability strategy now, not later",
        "Discuss the career opportunities in the growing green economy",
        "Share your honest take on corporate sustainability commitments",
    ],
    "Negotiation": [
        "Share the negotiation technique that works in business and life",
        "Discuss why the best negotiators focus on interests, not positions",
        "Explain the preparation framework that makes you a stronger negotiator",
        "Share a negotiation failure that taught you more than any win",
        "Talk about the power of silence in negotiations",
        "Discuss how to negotiate when you feel like you have no leverage",
        "Share the salary negotiation script that actually works",
        "Explain why win-win isn't just a cliché — it's the best strategy",
        "Discuss how to negotiate with someone more powerful than you",
        "Share the cross-cultural negotiation lesson that changed your approach",
    ],
    "Mentorship": [
        "Share how finding the right mentor changed your career path",
        "Discuss the difference between mentors, sponsors, and coaches",
        "Explain how to be a great mentee and get the most from mentorship",
        "Share the mentoring conversation that changed your perspective completely",
        "Talk about how to find a mentor when you don't have an obvious network",
        "Discuss why reverse mentoring is one of the most underrated practices",
        "Share the mistake you see mentees making repeatedly",
        "Explain how to structure an effective mentoring relationship",
        "Discuss why being a mentor made you better at your own job",
        "Share the best question a mentee ever asked you",
    ],
    "Layoffs and Job Market": [
        "Share how you navigated being laid off and came out stronger",
        "Discuss the emotional reality of layoffs that LinkedIn posts skip over",
        "Explain how to support a colleague who just got laid off",
        "Share the job search strategy that worked when everything felt hopeless",
        "Talk about what companies get wrong about how they handle layoffs",
        "Discuss how to rebuild your confidence after losing your job",
        "Share the unexpected silver lining of your layoff experience",
        "Explain how to keep your network warm so you're prepared for anything",
        "Discuss the job market trends professionals need to watch right now",
        "Share advice for hiring managers about treating laid-off candidates fairly",
    ],
    "Writing and Storytelling": [
        "Share the writing habit that improved all your professional communication",
        "Discuss why storytelling is the most underrated business skill",
        "Explain the writing framework that makes complex ideas simple",
        "Share how better writing skills led to better career opportunities",
        "Talk about the editing technique that makes your writing twice as clear",
        "Discuss why every professional should write regularly, even if they're not writers",
        "Share the storytelling structure that makes your presentations memorable",
        "Explain how to write for busy people who skim everything",
        "Discuss the difference between writing to impress and writing to communicate",
        "Share the writing resource that leveled up your skills the most",
    ],
    "Ethics in Business": [
        "Share a time when doing the right thing cost your company money (and why it was worth it)",
        "Discuss the ethical dilemma that still makes you think",
        "Explain why ethical leadership is good business, not just good morals",
        "Share how to build an ethical culture in a competitive industry",
        "Talk about the pressure to cut ethical corners and how to resist it",
        "Discuss the transparency decision that built trust with your customers",
        "Share the ethical framework you use when facing tough decisions",
        "Explain why whistleblower protection matters for every organization",
        "Discuss how to handle it when your company does something you disagree with",
        "Share the ethics lesson you learned from a business failure",
    ],
    "Team Building": [
        "Share the team building exercise that actually worked (not trust falls)",
        "Discuss how to build a high-performing team from scratch",
        "Explain the team dynamics lesson from sports that applies to business",
        "Share how you turned around a dysfunctional team",
        "Talk about why team building starts with individual conversations",
        "Discuss the role of conflict in building stronger teams",
        "Share the team ritual that improved morale and productivity",
        "Explain how to build trust in a new team of strangers",
        "Discuss why diverse teams are harder to manage but produce better results",
        "Share the team building mistake you'll never make again",
    ],
    "Time Management": [
        "Share the time management system that actually works for you",
        "Discuss why most time management advice doesn't account for knowledge work",
        "Explain the time audit exercise that changed how you spend your days",
        "Share how you protect your most productive hours",
        "Talk about the calendar hack that freed up 5+ hours per week",
        "Discuss why saying yes to everything is actually poor time management",
        "Share the batch processing technique that cut your task switching in half",
        "Explain the difference between urgent and important (with real examples)",
        "Discuss how to manage your energy, not just your time",
        "Share the time management lesson you learned from your biggest failure",
    ],
    "Sales Leadership": [
        "Share how you built a sales team culture that celebrates learning over closing",
        "Discuss the sales coaching technique that improved your team's performance",
        "Explain why the best sales leaders were not always the best individual sellers",
        "Share the sales process change that doubled your team's pipeline",
        "Talk about how to motivate a sales team without toxic competition",
        "Discuss the sales metrics that actually predict success vs. vanity metrics",
        "Share how you onboard new sales reps to get them productive faster",
        "Explain the territory planning approach that boosted your team's efficiency",
        "Discuss how to handle a sales rep who has great numbers but bad behavior",
        "Share the sales leadership lesson you learned from your team, not your boss",
    ],
    "Customer Experience": [
        "Share the customer experience moment that changed how you think about service",
        "Discuss why most companies overestimate how good their CX actually is",
        "Explain the customer journey mapping exercise that revealed huge gaps",
        "Share the small CX improvement that had a massive impact on retention",
        "Talk about how to create memorable customer experiences on a budget",
        "Discuss why speed of response matters more than perfection of response",
        "Share the customer complaint that led to your best product improvement",
        "Explain how to measure customer experience beyond satisfaction surveys",
        "Discuss the Amazon/Zappos CX principle that every company should steal",
        "Share how empowering frontline employees transformed your customer experience",
    ],
    "SaaS and Cloud": [
        "Share the SaaS growth lesson that took you years to learn",
        "Discuss why churn is the silent killer of SaaS businesses",
        "Explain the pricing model change that improved your SaaS metrics",
        "Share the cloud migration lesson from your own experience",
        "Talk about the SaaS metric every founder should obsess over",
        "Discuss product-led growth vs. sales-led growth — when to use each",
        "Share how to reduce SaaS customer churn with better onboarding",
        "Explain the build vs. buy decision framework for SaaS tools",
        "Discuss the future of SaaS — what's changing and what's staying",
        "Share the competitive analysis approach that improved your SaaS positioning",
    ],
    "Change Management": [
        "Share how you led a major organizational change without losing your team's trust",
        "Discuss why most change initiatives fail and what you'd do differently",
        "Explain the communication strategy that made a tough transition smoother",
        "Share the resistance to change you encountered and how you addressed it",
        "Talk about the change management framework that actually works in practice",
        "Discuss why change fatigue is real and how to manage it",
        "Share the lesson about change management timing you learned the hard way",
        "Explain how to get buy-in from stakeholders who are comfortable with the status quo",
        "Discuss the role of middle managers in successful change initiatives",
        "Share the organizational change that worked because of how it was communicated",
    ],
    "Emotional Intelligence": [
        "Share how emotional intelligence helped you navigate a workplace crisis",
        "Discuss the EQ skill that matters most for professional success",
        "Explain how to read a room better in meetings and negotiations",
        "Share the self-awareness practice that transformed your leadership",
        "Talk about the difference between empathy and sympathy at work",
        "Discuss how to manage your emotions during high-pressure situations",
        "Share the emotional intelligence lesson that improved your relationships at work",
        "Explain why EQ matters more than IQ for leadership roles",
        "Discuss how to develop emotional intelligence as an adult",
        "Share the situation where low EQ cost someone (maybe you) a great opportunity",
    ],
    "Cybersecurity": [
        "Share the cybersecurity lesson every non-technical leader needs to know",
        "Discuss why cybersecurity is everyone's responsibility, not just IT's",
        "Explain the security practice that every company should implement today",
        "Share the cybersecurity incident that changed your company's approach",
        "Talk about the human element in cybersecurity — why training matters",
        "Discuss the biggest cybersecurity myths that put businesses at risk",
        "Share the password and authentication advice professionals need right now",
        "Explain how to build a security-first culture without creating paranoia",
        "Discuss the cybersecurity career path for non-traditional backgrounds",
        "Share the phishing attempt that almost fooled you and what you learned",
    ],
    "Legal and Compliance": [
        "Share the compliance lesson that saved your company from a costly mistake",
        "Discuss why every startup needs legal counsel earlier than they think",
        "Explain the contract clause that professionals should always negotiate",
        "Share how regulatory changes created unexpected opportunities in your industry",
        "Talk about the intellectual property mistake that too many founders make",
        "Discuss why data privacy compliance is a competitive advantage, not just a cost",
        "Share the employment law basics every manager should understand",
        "Explain how to work effectively with legal teams without slowing everything down",
        "Discuss the compliance training approach that actually changes behavior",
        "Share the legal risk you didn't see coming and what it taught you",
    ],
}

# Flatten all topics into a single list for easy iteration
ALL_TOPICS = []
for category, topics in TOPICS.items():
    for topic in topics:
        ALL_TOPICS.append({"category": category, "topic": topic})

assert len(ALL_TOPICS) == 500, f"Expected 500 topics, got {len(ALL_TOPICS)}"
